lub62/lub62/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace lub62.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Foto { get; set; }
        public IEnumerable<Dish> Dishes { get; set; }
        public IEnumerable<Bascket> Basckets { get; set; }
    }
}

lub62/lub62/Controllers/BascketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lub62.Data;
using lub62.Models;
using Microsoft.AspNetCore.Identity;

namespace lub62.Controllers
{
    public class BascketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public BascketsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        [HttpPost]
        public async Task<IActionResult> CreateBascket(int dishId, int restaurantId, int bascketId)
        {
            Bascket bascket = await _context.Bascket.FirstOrDefaultAsync(c => c.Id == bascketId);
            
            Restaurant restaurant = await _context.Restaurant.FirstOrDefaultAsync(c => c.Id == restaurantId);
            Dish dish = await _context.Dish.FirstOrDefaultAsync(c => c.Id == dishId);
            // List<Dish> dishes = await _context.Dish.Where(c => c.RestaurantId == restaurantId).ToListAsync();

            bascket.Dishes.Add(dish);
            
            return View(bascket);
        }
    }
}

lub62/lub62/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lub62.Data;
using lub62.Models;
using System.IO;
using lub62.Service;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;


namespace lub62.Controllers
{
    public class RestaurantsController : Controller
    {
        
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;
        private readonly ApplicationDbContext _context;

        public RestaurantsController( FileUploadService fileUploadService, IHostingEnvironment environment, UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            
            _environment = environment;
            _userManager = userManager;
            _fileUploadService = fileUploadService;
            _context = context;
        }
    

        public async Task<IActionResult> IndexOneRestourant(int  id)
        {

            var user = await _userManager.GetUserAsync(User);
            List<Dish> dishesInBascket = new List<Dish>();
            Bascket bascket = new Bascket()
            {
                RestaurantId = id,
                ApplicationUserId = user.Id,
                Dishes = dishesInBascket
            };

            _context.Add(bascket);
            await _context.SaveChangesAsync();

            Restaurant restaurant =await _context.Restaurant.FirstOrDefaultAsync(c => c.Id == id);
            List<Dish> dishes = _context.Dish.Where(d => d.RestaurantId == restaurant.Id).ToList();
            ViewBag.dishesInRestaurant = dishes;
            BascketOfRestaurantViewModel model = new BascketOfRestaurantViewModel()
            {
                Restaurant = restaurant,
                Bascket = bascket
            };
            if (restaurant == null)
            {
                return NotFound();
            }
            return View(model);
        }
        // GET: Restaurants
        public async Task<IActionResult> Index()
        {
            return View(await _context.Restaurant.ToListAsync());
        }

      

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRestaurentViewModel model)
        {
            var path = Path.Combine(_environment.WebRootPath, $"image\\{model.Name}");
            _fileUploadService.Upload(path, model.Foto.FileName, model.Foto);
            Restaurant restaurant = new Restaurant()
            {
                Foto = $"image/{model.Name}/{model.Foto.FileName}",
                Name = model.Name,
                Info = model.Info
            };
            if (ModelState.IsValid)
            {
                _context.Add(restaurant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant.FindAsync(id);
            if (restaurant == null)
            {
                return NotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Info,Foto")] Restaurant restaurant)
        {
            if (id != restaurant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(restaurant);
        }

        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurant = await _context.Restaurant.FindAsync(id);
            _context.Restaurant.Remove(restaurant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
            return _context.Restaurant.Any(e => e.Id == id);
        }
    }
}

lub62/lub62/Views/Restaurants/Create.cshtml
@model CreateRestaurentViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
   
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Info" class="control-label"></label>
                    <input asp-for="Info" class="form-control" />
                    <span asp-validation-for="Info" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Foto"></label><br />
                    <input class=" = form-control" type="file" name="Foto" accept="image/*" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lub62/lub62/Views/Restaurants/Delete.cshtml
@model lub62.Models.Restaurant

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

lub62/lub62/Views/Restaurants/Details.cshtml
@model lub62.Models.Restaurant

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Info)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Info)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

lub62/lub62/Views/Restaurants/Edit.cshtml
@model lub62.Models.Restaurant

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Info" class="control-label"></label>
                <input asp-for="Info" class="form-control" />
                <span asp-validation-for="Info" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

lub62/lub62/Views/Restaurants/Index.cshtml
@model IEnumerable<lub62.Models.Restaurant>

<h2>Рестораны</h2>

{
<table class="table">
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="IndexOneRestourant" asp-controller="Restaurant" asp-route-name="@item.Name">@item.Name</a>
                </td>
                <td>
                    <img src="~/@item.Foto" width="100" height="100" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Info)
                </td>
            </tr>

        }
    </tbody>
</table>

lub62/lub62/Views/Restaurants/IndexOneRestourant.cshtml
@model lub62.Models.BascketOfRestaurantViewModel


<table class="table">
    <tbody>
        <tr>
            <td>
                @Model.Restaurant.Name
            </td>
            <td>
                <img src="~/@Model.Restaurant.Foto" width="100" height="100" />
            </td>
            <td>
                @Model.Restaurant.Info
            </td>
        </tr>
    </tbody>
</table>
<table class="table">
    <thead>
        <tr>
            <th>
                Название блюда
            </th>
            <th>
                Цена
            </th>
            <th>
                Информация
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (Dish d in ViewBag.dishesInRestaurant)
        {
            <tr>
                <td>
                    @d.Name
                </td>
                <td>
                    @d.Price
                </td>
                <td>
                    @d.Info
                </td>
                <td>
                    <input type="button" onclick="CreateBascket('@d.Id','@Model.Restaurant.Id',@Model.Bascket.Id)" value="Добавить в корзину" />
                </td>
            </tr>
        }
    </tbody>
</table>

<h3>Корзина</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Блюда в корзине
            </th>
            <th>
                Колличество блюд
            </th>
            <th>
                Общая сумма
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Bascket.Dishes.Count()>0)
        { <tr>
                <td>
                    @foreach (Dish d in Model.Bascket.Dishes)
                    {
                        @d.Name
                    }
                </td>
                <td>
                    @Model.Bascket.Dishes.Count()
                </td>
                <td>
                    @(Model.Bascket.Dishes.Sum(x => x.Price) / Model.Bascket.Dishes.Count());
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    function CreateBascket(dishId, restaurantId, bascketId)
    {
            $.ajax({
                url: '@Url.Action("CreateBascket", "Basckets")',
                type: 'POST',
                data: { 'dishId': dishId, 'restaurantId': restaurantId, 'bascketId': bascketId},
                success: ('ok'),
                error: console.log('ошибка')
                });
    }
</script>